---
title: "SPPU_StatisticalAnalysis"
author: "Elise"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: false 
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "C:/Users/elise/Documents/Mémoire/Main/Data/Templates/SPPU")
```

```{r include=FALSE}
WDIR <- "C:/Users/elise/Documents/Mémoire/Main/Data"
subdir <- 'Extracted'
datadir <- sprintf( '%s/%s', WDIR, subdir)

library(statgenHTP)
library(ggplot2)
library(gridExtra)
library(dplyr)
library(lubridate)
library(readxl)
library(janitor)
library(flextable)
library(skimr)
library(rstatix)
library(visreg)
library(lsmeans)
library(car)
library(scales)
library(viridis)
library(ggforce)
library(asreml)
library(patchwork)
library(lme4)
library(lmerTest)
library(desplot)
# Import functions
source("~/Mémoire/Main/Source/functions.R")


list.files()

plant_info <- read.table("plant_info.txt", header = TRUE, sep = "\t")

# plant_info
plant_info <- lapply(plant_info, factor)

```



# Statistical modeling for phenotypic traits

No data for end-of-experiment variables. 


